### ISSUE TITLE
recordAsync: Expected a Camera component

### ISSUE THREAD

**Issue by BroshkovD** [react-native-camera/react-native-camera#1495]
### Which implementation are you using

RNCamera @ 1.0.3

### Steps to reproduce
import { RNCamera } from 'react-native-camera'

handleRecordVideo = async function () {
    if (this.camera) {
      const data = await this.camera.recordAsync()
      console.warn('Video output:', data)
    }
  }

  render () {
    return (
      <View style={styles.container}>
        <RNCamera
          ref={ref => {
            this.camera = ref
          }}
          style={styles.preview}
          permissionDialogTitle={'Permission to use camera'}
          permissionDialogMessage={'We need your permission to use your camera phone'}
        />
      </View>
    )
  }

### Expected behaviour
A video should be recorded and URI should be shown on console.warn

### Actual behaviour
After starting record got the warning
![image](https://user-images.githubusercontent.com/18656203/38944034-80c7462c-433b-11e8-932e-f3dc6f7d465c.png)

Btw on **Android 5.1** it works without any problem the problem only with the version Android above 7

Also, I've noticed that it work on **targetSdkVersion 22** or less but has not stable behaviour and some time this issue has appeared again. 

### Environment
- **Node.js version**: 9.6.1
- **React Native version**: 0.55.2
- **React Native platform + platform version**:  Android 8.0.0 && 8.1.0 etc

### react-native-camera
**Version**:  1.0.3

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
The promise only resolves when you call `stopRecording`, are you calling it somewhere?

Does `takePictureAsync()` work without any problems for you?

This way we can narrow down if the error is on the camera not being mounted or on the recording method of the camera view.

**Comment by coryarmbrecht** [comment]
I have this issue, and am using 
```
handleStopVideo = () => {
    this.camera.stopRecording()
}
```

**Comment by sibelius** [comment]
can u provide the fullstack trace? native one as well?

**Comment by coryarmbrecht** [comment]
```
YellowBox.js:82 Possible Unhandled Promise Rejection (id: 0):
Error: recordAsync: Expected a Camera component
Error: recordAsync: Expected a Camera component
    at createErrorFromErrorData (blob:http://localhost:8081/c0d3b691-8e92-4017-a0a5-86d0f9a34298:2025:17)
    at blob:http://localhost:8081/c0d3b691-8e92-4017-a0a5-86d0f9a34298:1977:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/c0d3b691-8e92-4017-a0a5-86d0f9a34298:2419:18)
    at blob:http://localhost:8081/c0d3b691-8e92-4017-a0a5-86d0f9a34298:2164:18
    at MessageQueue.__guardSafe (blob:http://localhost:8081/c0d3b691-8e92-4017-a0a5-86d0f9a34298:2332:11)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/c0d3b691-8e92-4017-a0a5-86d0f9a34298:2163:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58
console.warn @ YellowBox.js:82
onUnhandled @ Promise.js:44
onUnhandled @ rejection-tracking.js:71
(anonymous) @ JSTimers.js:258
_callTimer @ JSTimers.js:154
callTimers @ JSTimers.js:407
__callFunction @ MessageQueue.js:353
(anonymous) @ MessageQueue.js:118
__guardSafe @ MessageQueue.js:316
callFunctionReturnFlushedQueue @ MessageQueue.js:117
(anonymous) @ debuggerWorker.js:72
```

**Comment by sibelius** [comment]
could u get the native crashes as well?

`adb logcat`?

**Comment by coryarmbrecht** [comment]
adb logcat output: https://gist.github.com/coryarmbrecht/53a06934da3a4d46cd0b37e905a36105

**Comment by jgfidelis** [comment]
For documentation, this is the crash, if someone wants to take a look.
```
--------- beginning of crash
04-18 09:11:26.741  2913  2913 E AndroidRuntime: FATAL EXCEPTION: main
04-18 09:11:26.741  2913  2913 E AndroidRuntime: Process: com.myapp, PID: 2913
04-18 09:11:26.741  2913  2913 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {com.myapp/com.myapp.MainActivity}: java.lang.IllegalStateException
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3912)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.-wrap15(Unknown Source:0)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: Caused by: java.lang.IllegalStateException
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.media.MediaRecorder.stop(Native Method)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.google.android.cameraview.Camera1.stop(Camera1.java:145)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.google.android.cameraview.CameraView.stop(CameraView.java:299)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at org.reactnative.camera.RNCameraView.onHostPause(RNCameraView.java:349)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:214)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveToBeforeResumeLifecycleState(ReactInstanceManager.java:676)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:510)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:529)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:96)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onPause(ReactActivity.java:60)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7143)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
04-18 09:11:26.741  2913  2913 E AndroidRuntime: 	... 11 more
```

**Comment by mannol** [comment]
After adding a meaningful logging to CameraModule.java record(), I've come to the following conclusion (based on the log output: `mediaRecorder.setAudioSource failed`): __Camera is missing a RECORD_AUDIO permission__. That's why it works normally on Android < 6 (you mentioned 5.1). because older versions of android had the permissions set through manifest file. Also, that's the reason why recording works when you set the `mute` option.

Cheers.

**Comment by zouminhuababa** [comment]
I have this issue too, how to solve it?

**Comment by Samsinite** [comment]
@zouminhuababa and anyone else finding this issue, use https://facebook.github.io/react-native/docs/permissionsandroid and request permission for `PermissionsAndroid.PERMISSIONS.RECORD_AUDIO`
